sdii/journal/urls.py
# ------------------------------------||------------------------------------- #
#                               journal/urls.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
# ------------------------------------||------------------------------------- #

from django.conf.urls import patterns, url
from journal import views

urlpatterns = patterns('',
    # /journal/                   
    url(r'^$', views.journalIndexPage, name='journalIndexPage'),

    # /journal/<journal_id>/ ---> the (?P<journal_id>\d+) tells Django to read a number from the url pass it as journal_id to the view
    url(r'^(?P<journal_id>\d+)/$', views.journalEntryPage, name='journalEntryPage'),

    # /journal/<journal_id>/update ---> url for updating a specific journal entry
    url(r'^(?P<journal_id>\d+)/update/$', views.journalEntryUpdatePage, name='journalEntryUpdatePage'),

    # /journal/<journal_id>/submit/ ---> handles the form submittal from journalEntryPage
    url(r'^(?P<journal_id>\d+)/submit/$', views.journalSubmitEntry, name='journalSubmitEntry'),

    # /journal/<journal_id>/update/submit/ ---> a place holder for a function that handles the form submittal from journalEntryPage
    url(r'^(?P<journal_id>\d+)/update/submit/$', views.journalSubmitEntryUpdate, name='journalSubmitEntryUpdate'),

    # /journal/all/ ---> url for page that displays all entries for a user
    url(r'^all/$', views.journalUserPage, name='journalUserPage'),

    # /journal/<journal_id>/concept-map-image/ ---> link for the concept map png image
    url(r'^(?P<journal_id>\d+)/concept-map-image/$', views.journalConceptMapImage, name='journalConceptMapImage'),

    # /journal/example/concept-map/ ---> displays the example concept map input and output
    url(r'^example/concept-map/$', views.journalExampleConceptMapPage, name='journalExampleConceptMapPage'),
)

# (?P<username>\w+)     ---> w+ indicates a string
# (?P<journal_id>\d+)   ---> d+ indicates a number

sdii/sdii/urls.py
# ------------------------------------||------------------------------------- #
#                                 sdii/urls.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
#
# Description:
#   The master url file that routes page requests to the specified locations
# ------------------------------------||--------------------------------------#

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sdii.views.home', name='home'),
    # url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^$', 'home.views.homePage', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^journal/', include('journal.urls', namespace='journal')),
    url(r'^registration/', include('registration.urls', namespace='registration')),

    # DO NOT CHANGE THE FOLLOWING - these are for the operation of the built in authentication for Django
    # Taken from C:\Anaconda\Lib\site-packages\django\contrib\auth\urls.py
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),  
)

sdii/journal/models.py
# ------------------------------------||------------------------------------- #
#                               journal/models.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
# ------------------------------------||------------------------------------- #

import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

# contains information on the journal for the student assignment
class Journal(models.Model):
    title = models.TextField('Title')                                           # the name in '' will the be verbose name for the field
    instructions = models.TextField('Instructions')
    date = models.DateTimeField('Date Created', default=datetime.datetime.now)
    
    def __unicode__(self):                                                      # defines what is returned when the model is called directly
        return self.title
    
    def was_published_recently(self):                                           # defines a method that can be accesed in the site admin
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.date <= now             # returns a boolean if the date of the Journal is in the range
        
    was_published_recently.admin_order_field = 'date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'

# contains the actual student entries for the journal
class JournalEntry(models.Model):
    JOURNAL_TYPE_CHOICES = (
        ('Journal Entry', 'Journal Entry'),
        ('Concept Map', 'Concept Map'),    
    )                                           # first entry is value to be set on the model; second entry is the display name
    
    journal = models.ForeignKey(Journal)
    author = models.ForeignKey(User)    
    course = models.TextField('Course')
    topic = models.TextField('Topic')  
    journal_type = models.TextField('Journal Type', choices=JOURNAL_TYPE_CHOICES, default=JOURNAL_TYPE_CHOICES[0][0])
    entry = models.TextField('Entry')
    date_submitted = models.DateTimeField('Date Submitted', default=datetime.datetime.now)
        
    def __unicode__(self):                                                      # defines what is returned when the model is called directly
        return self.journal.title
    
    def person_name(self):                                                      # defines a method for getting the user's name from the model
        return self.author.first_name + ' ' + self.author.last_name
    
    person_name.short_description = 'Author'
    
    class Meta:                                                                 # defines options for the model itself
        verbose_name_plural = 'Journal Entries';                                # sets the plural human readable name

sdii/journal/views.py
# ------------------------------------||------------------------------------- #
#                               journal/views.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
# ------------------------------------||------------------------------------- #

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from journal.models import Journal, JournalEntry
import pydot

@login_required                                                                         # requires a site log in before access
def journalIndexPage(request):                                                          # page containing the index of available journals
    journals = Journal.objects.order_by('date')                                         # attempts to grab the Journal objects from database and sort ascending by date field ('-date' orders descending)
    
    if journals:                                                                        # if there are journals available
        author = User.objects.get(username=request.user.username)                       # get the user requesting the page
        journal_entry = []                                                              # initialize
        number = []
        i = 1
    
        for j in journals:                                                                  # work through each journal entry
            if JournalEntry.objects.filter(author=author).filter(journal=j).exists():       # if an entry exists for this journal
                journal_entry.append(JournalEntry.objects.get(journal=j, author=author))    # get the specific entry
            else:
                journal_entry.append('')                                                    # leave slot for that journal empty
            
            number.append(i)                                                                # save the journal number we are on
            i += 1                                                                          # increment
            
        zipped_var = zip(number, journals, journal_entry)                         # matches the indexes to create one giant iterable
  
    else:
        zipped_var = []
        
    return render(request, 'journal/journalIndexPage.html', {'zipped_var': zipped_var}) # uses the template 'journal/journalIndexPage.html' and passes zipped variables to template


@login_required                                                                         # requires a site log in before access
def journalEntryPage(request, journal_id):                                              # page containing the form for submitting a journal entry
    selectedJournal = get_object_or_404(Journal, pk=journal_id)                         # attempts to load the journal based on the id supplied
    return render(request,'journal/journalEntryPage.html', {'selectedJournal': selectedJournal})


@login_required                                                                         # requires a site log in before access
def journalUserPage(request):                                                           # page containing all the user journal submissions
    author = User.objects.get(username=request.user.username)
    user_journals = JournalEntry.objects.filter(author=author)
    user_entries = []    
    
    for uj in user_journals:
        if uj.journal_type == 'Journal Entry':
            user_entries.append('<br />'.join(uj.entry.split('\n')))            
            
        elif uj.journal_type == 'Concept Map':    
            begin_img = uj.entry.find('***')                                                # find the begining of the graphviz code for image
            end_img = uj.entry.find('***', begin_img+1) + 4                                 # find the end of the graphviz code for image; +4 puts the location after the '***'
            
            before_text = '<br />'.join(uj.entry[:begin_img].split('\n'))                   # do this to switch from text format to html format for rendering       
            after_text = '<br />'.join(uj.entry[end_img:].split('\n'))                      # do this to switch from text format to html format for rendering
            user_entries.append([before_text, after_text])           
        
    zvar = zip(user_journals, user_entries)                                             # matches indices for looping using Django in the template
    return render(request,'journal/journalUserPage.html', {'zvar': zvar, 'author': author})


@login_required                                                                         # requires a site log in before access 
def journalSubmitEntry(request, journal_id):                                            # form submission handler for journalEntryPage
    journal = Journal.objects.get(pk=journal_id)
    author = User.objects.get(username=request.user.username)
    
    if JournalEntry.objects.filter(author=author).filter(journal=journal).exists():     # send user to the update page since a journal entry has already been submitted
        return HttpResponseRedirect(reverse('journal:journalEntryUpdatePage', args=(journal_id,)))
    else:           
        je_obj = JournalEntry(journal=journal, 
                              author=author, 
                              course=request.POST['course'], 
                              topic=request.POST['topic'], 
                              journal_type=request.POST['journal_type'],
                              entry=request.POST['entry'].split('\n'))
        je_obj.save()    
    
    return HttpResponseRedirect(reverse('journal:journalUserPage'))


@login_required                                                                                                                 # requires a site log in before access 
def journalEntryUpdatePage(request, journal_id):                                                                                # page for updating a journal entry
    current_entry = JournalEntry.objects.get(journal__id = journal_id, author__username = request.user.username)                # get the current entry for the journal we are updating

    if current_entry.journal_type == 'Journal Entry':
        entry = '<br />'.join(current_entry.entry.split('\n'))
        
    elif current_entry.journal_type == 'Concept Map':    
        begin_img = current_entry.entry.find('***')                                     # find the begining of the graphviz code for image
        end_img = current_entry.entry.find('***', begin_img+1) + 4                      # find the end of the graphviz code for image; +4 puts the location after the '***'
            
        before_text = '<br />'.join(current_entry.entry[:begin_img].split('\n'))                   # do this to switch from text format to html format for rendering       
        after_text = '<br />'.join(current_entry.entry[end_img:].split('\n'))                      # do this to switch from text format to html format for rendering          

        entry = [before_text, after_text]

    return render(request,'journal/journalEntryUpdatePage.html', {'current_entry': current_entry, 'entry': entry})


@login_required                                                                                                                 # requires a site log in before access 
def journalSubmitEntryUpdate(request, journal_id):                                                                              # form submission handler for journalEntryUpdatePage
    je_obj = JournalEntry.objects.get(journal__id = journal_id, author__username = request.user.username)                       # get the associated entry for the journal
    
    je_obj.course = request.POST['course']                                              # update fields; ignore author and journal fields as these would not change
    je_obj.topic = request.POST['topic']
    je_obj.journal_type = request.POST['journal_type']
    je_obj.entry = request.POST['entry']

    je_obj.save()                                                                       # save updates
    
    return HttpResponseRedirect(reverse('journal:journalUserPage'))                     # send user to the overview page


def journalExampleConceptMapPage(request):
    return render(request, 'journal/journalExampleConceptMapPage.html')

def journalConceptMapImage(request, journal_id):
    journal_entry = JournalEntry.objects.get(journal__id = journal_id, author__username = request.user.username) # get journal entry we are working with
    
    begin_img = journal_entry.entry.find('***') + 4                 # find the tag that indicates the beginning of the figure; +4 moves the marker to after the ***
    end_img = journal_entry.entry.find('***', begin_img+1) - 1      # find the tag that indicates the end of the figure; -1 moves the marker to before the ***
    
    img_code = journal_entry.entry[begin_img:end_img]   # truncate the entry to just the image code
    
    row_ends = [0]                                      # prime the row_ends list
    loc = 0                                             # prime the end-of-line location
            
    while loc != -1:                                    # while the location of the end of the line (indicated by \n) is found -> (-1) means the string was not found
        loc = img_code.find('\n', loc+1)                # get the location of the next end-of-line
                
        if loc != -1:                                   # if end-of-line found

sdii/journal/templates/journal/journalEntryPage.html
<!------------------------------------||------------------------------------- #
#             journal/templates/journal/journalEntryPage.html
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
#
# Description:
#   The web script for the display of the entry page of the journals
# ------------------------------------||-------------------------------------->

{% extends "base.html" %}   <!--Uses the site template-->
{% load i18n %}             <!--loads Django translation tags-->

{% block content %}         <!--Replaces the content block on the site template-->
    <h2>{% trans selectedJournal.title %}</h2>                                      
    
    <h3>Instructions</h3>                                                           {% comment "The {{}} loads Django variables passed from the view" %}{% endcomment %}
    <p>{% trans selectedJournal.instructions %}</p>                                 {% comment "The {% trans  %} translates the string to the browser language" %}{% endcomment %}
    <table style="border-spacing:5px;">
        <tr>
            <th colspan="4" style="font-weight:normal;text-align:left;"><i>{% trans 'Concept Map Markups:' %}</i></th>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>***</td>
            <td></td>
            <td>{% trans 'begin/end image code' %}</td>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>A ==> B</td>
            <td></td>
            <td>{% trans 'connect two nodes without a connector label' %}</td>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>A = {% trans 'label' %} => B</td>
            <td></td>
            <td>{% trans 'connect two nodes with a connector label' %}</td>
        </tr>
    </table>
    <p>An example concept map with accompanying code can be found <a href="{% url 'journal:journalExampleConceptMapPage' %}">here</a>.</p>         
                                                                           
    <h3>Entry</h3>
    <form action="{% url 'journal:journalSubmitEntry' selectedJournal.id %}" method="post">     {% comment "the variable after the '' is used to fill in the url" %}{% endcomment %}
        {% csrf_token %}                                                                        {% comment "The {% csrf_token %} provided by Django should be with all forms for cross site request forgeries protection" %}{% endcomment %}                                                     
        <table style="border-spacing:5px;">
            <tr>
                <td>Course:</td>
                <td><input type="text" name="course" required></td>
            </tr>
            <tr>
                <td>Topic:</td>
                <td><input type="text" name="topic" required></td>
            </tr>
            <tr>
                <td>Type:</td>
                <td><input type="radio" name="journal_type" value="Journal Entry" required>{% trans 'Journal Entry' %}
                    <input type="radio" name="journal_type" value="Concept Map" required>{% trans 'Concept Map' %}</td>
            </tr>
            <tr>
                <td style="vertical-align:text-top;">{% trans 'Entry:' %}</td>
                <td><textarea name="entry" rows="25" cols="75" required></textarea></td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align:right;"><input type="submit" value="Submit"></td>
            </tr>
        </table>
    </form>
{% endblock %}

sdii/journal/templates/journal/journalEntryUpdatePage.html
<!------------------------------------||------------------------------------- #
#          journal/templates/journal/journalEntryUpdatePage.html
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 September 15
#
# Description:
#   The web script for updating a journal entry
# ------------------------------------||-------------------------------------->

{% extends "base.html" %}   <!--Uses the site template-->
{% load i18n %}             <!--loads Django translation tags-->

{% block content %}         <!--Replaces the content bloxk on the site template-->
    <h2>{% trans 'Update Journal Entry' %}</h2>
    <p>{% trans 'Look over your past submission for this journal and make any necessary changes below.' %}</p>
    <h3>{% trans 'Previous Submission:' %}</h3>

    <fieldset>
        <legend style="font-weight:bold">{% trans current_entry.journal.title %} - {{ current_entry.date_submitted }}</legend>
        <table style="border-spacing:5px;">
            <tr>
                <td>{% trans 'Instructions:' %}</td>
                <td>{{ current_entry.journal.instructions }}</td>
            </tr>
            <tr>
                <td>{% trans 'Course:' %}</td>
                <td>{{ current_entry.course }}</td>
            </tr>
            <tr>
                <td>{% trans 'Topic:' %}</td>
                <td>{{ current_entry.topic }}</td>
            </tr>
            <tr>
                <td>{% trans 'Type:' %}</td>
                <td>{{ current_entry.journal_type }}</td>
            </tr>
            <tr>
                <td style="vertical-align:text-top;">{% trans 'Entry:' %}</td>
                <td>
                    {% if current_entry.journal_type == 'Journal Entry' %}
                        {{ entry|safe }}
                    {% elif current_entry.journal_type == 'Concept Map' %}                    
                        {{ entry.0|safe }}<br>
                        <img src="{% url 'journal:journalConceptMapImage' current_entry.journal.id %}" alt="Concept Map Image"><br>
                        {{ entry.1|safe }}
                    {% endif %}
                </td>
            </tr>
        </table>
    </fieldset>
    <h3>{% trans 'New Submission:' %}</h3>
    <p>{% trans 'Make edits to this journal entry below. Click update to apply changes. Be certain about any changes you make as the previous entry will be erased.' %}</p>
    <table style="border-spacing:5px;">
        <tr>
            <th colspan="3" style="font-weight:normal;text-align:left;"><i>{% trans 'Concept Map Markups:' %}</i></th>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>***</td>
            <td></td>
            <td>{% trans 'begin/end image code' %}</td>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>A ==> B</td>
            <td></td>
            <td>{% trans 'connect two nodes without a connector label' %}</td>
        </tr>
        <tr>
            <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
            <td>A = label => B</td>
            <td></td>
            <td>{% trans 'connect two nodes with a connector label' %}</td>
        </tr>
    </table>
    <p>An example concept map with accompanying code can be found <a href="{% url 'journal:journalExampleConceptMapPage' %}">here</a>.</p>    

    <form action="{% url 'journal:journalSubmitEntryUpdate' current_entry.journal.id %}" method="post">
        {% csrf_token %}                                                    
        <table style="border-spacing:5px;">
            <tr>
                <td>Course:</td>
                <td><input type="text" name="course" value="{{ current_entry.course }}" required></td>
            </tr>
            <tr>
                <td>Topic:</td>
                <td><input type="text" name="topic" value="{{ current_entry.topic }}" required></td>
            </tr>
            <tr>
                <td>Type:</td>
                <td>{% if current_entry.journal_type == 'Journal Entry' %}
                        <input type="radio" name="journal_type" value="Journal Entry" checked="checked" required>{% trans 'Journal Entry' %}
                        <input type="radio" name="journal_type" value="Concept Map" required>{% trans 'Concept Map' %}
                    {% else %}
                        <input type="radio" name="journal_type" value="Journal Entry" required>{% trans 'Journal Entry' %}
                        <input type="radio" name="journal_type" value="Concept Map" checked="checked" required>{% trans 'Concept Map' %}
                    {% endif %}</td>
            </tr>
            <tr>
                <td style="vertical-align:text-top;">{% trans 'Entry:' %}</td>
                <td><textarea name="entry" rows="25" cols="75" required>{{ current_entry.entry }}</textarea></td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align:right;"><input type="submit" value="Update"></td>
            </tr>
        </table>
    </form>
{% endblock %}

sdii/journal/templates/journal/journalIndexPage.html
<!------------------------------------||------------------------------------- #
#             journal/templates/journal/journalIndexPage.html
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
#
# Description:
#   The web script for the display of the list of journals
# ------------------------------------||-------------------------------------->

{% extends "base.html" %}   <!--Uses the site template-->
{% load i18n %}             <!--loads Django translation tags-->

{% block content %}         <!--Replaces the content bloxk on the site template-->
    <h2>{% trans 'List of Journals' %}</h2>
    
    {% trans 'Below are the list of journals assigned. Click' %} <a href="{% url 'journal:journalUserPage' %}">{% trans 'here' %}</a> {% trans ' to view all submitted journal entries.' %}
    <br>
    <br>    
    {% if zipped_var %}
        <table style="border-spacing:5px; text-align:left;">
            
            <tr>
                <th style="padding:5px;">{% trans 'No.' %}</th>
                <th style="padding:5px;">{% trans 'Date Published' %}</th>
                <th style="padding:5px;">{% trans 'Journal' %}</th>
                <th style="padding:5px;">{% trans 'Date Submitted' %}</th>
            </tr>
            {% for number, journal, journal_entry in zipped_var %}
                <tr>
                    <td style="padding:5px;">{{ number }}</td>
                    <td style="padding:5px;">{{ journal.date }}</td>
                    {% if journal_entry %}
                        <td style="padding:5px;">{% trans journal.title %}</td>
                        <td style="padding:5px;">{{ journal_entry.date_submitted }}</td>
                        <td style="padding:5px;">(<a href="{% url 'journal:journalEntryUpdatePage' journal.id %}">{% trans 'Edit' %}</a>)</td>
                    {% else %}
                        <td style="padding:5px;">{% trans journal.title %}</td>
                        <td style="padding:5px;"></td>
                        <td style="padding:5px;">(<a href="{% url 'journal:journalEntryPage' journal.id %}">{% trans 'Create Entry' %}</a>)</td>
                    {% endif %}                   
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>{% trans 'No journals are available.' %}</p>
    {% endif %}
{% endblock %}

sdii/journal/templates/journal/journalUserPage.html
<!------------------------------------||------------------------------------- #
#             journal/templates/journal/journalEntryPage.html
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
#
# Description:
#   The web script for the display of the all of a user's journals
# ------------------------------------||-------------------------------------->

{% extends "base.html" %}   <!--Uses the site template-->
{% load i18n %}             <!--loads Django translation tags-->

{% block content %}         <!--Replaces the content bloxk on the site template-->
    <h2>{% trans 'Journals Submitted' %}</h2>
    {% trans 'Author:' %} {{ author.first_name }} {{ author.last_name }}
    <br>
    <br>
    {% for journal, entry in zvar %}
    <fieldset>
        <legend style="font-weight:bold"> {% trans journal.journal.title %} - {{ journal.date_submitted }} (<a href="{% url 'journal:journalEntryUpdatePage' journal.journal.id %}">{% trans 'Edit' %}</a>)</legend>
        <table style="border-spacing:5px;">
            <tr>
                <td>{% trans 'Instructions:' %}</td>
                <td>{{ journal.journal.instructions }}</td>
            </tr>
            <tr>
                <td>{% trans 'Course:' %}</td>
                <td>{{ journal.course }}</td>
            </tr>
            <tr>
                <td>{% trans 'Topic:' %}</td>
                <td>{{ journal.topic }}</td>
            </tr>
            <tr>
                <td>{% trans 'Type:' %}</td>
                <td>{{ journal.journal_type }}</td>
            </tr>
            <tr>
                <td style="vertical-align:text-top;">{% trans 'Entry:' %}</td>
                <td>
                    {% if journal.journal_type == 'Journal Entry' %}
                        {{ entry|safe }}
                    {% elif journal.journal_type == 'Concept Map' %}
                        {{ entry.0|safe }}<br>                                                                                                                   <!--the .0 indicates the 0th indices of the list-->
                        <img src="{% url 'journal:journalConceptMapImage' journal.journal.id %}" alt="Concept Map for Journal #{{journal.journal.id}}"><br>      <!--This url calls a view which renders the graphviz image-->
                        {{ entry.1|safe }}
                    {% endif %}
                </td>
            </tr>
        </table>
    </fieldset>
    <br>
    {% endfor %}
{% endblock %}