sdii/journal/urls.py
# ------------------------------------||------------------------------------- #
#                               journal/urls.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
# ------------------------------------||------------------------------------- #

from django.conf.urls import patterns, url
from journal import views

urlpatterns = patterns('',
    # /journal/                   
    url(r'^$', views.journalIndexPage, name='journalIndexPage'),

    # /journal/<journal_id>/ ---> the (?P<journal_id>\d+) tells Django to read a number from the url pass it as journal_id to the view
    url(r'^(?P<journal_id>\d+)/$', views.journalEntryPage, name='journalEntryPage'),

    # /journal/<journal_id>/update ---> url for updating a specific journal entry
    url(r'^(?P<journal_id>\d+)/update/$', views.journalEntryUpdatePage, name='journalEntryUpdatePage'),

    # /journal/<journal_id>/submit/ ---> handles the form submittal from journalEntryPage
    url(r'^(?P<journal_id>\d+)/submit/$', views.journalSubmitEntry, name='journalSubmitEntry'),

    # /journal/<journal_id>/update/submit/ ---> a place holder for a function that handles the form submittal from journalEntryPage
    url(r'^(?P<journal_id>\d+)/update/submit/$', views.journalSubmitEntryUpdate, name='journalSubmitEntryUpdate'),

    # /journal/all/ ---> url for page that displays all entries for a user
    url(r'^all/$', views.journalUserPage, name='journalUserPage'),

    # /journal/<journal_id>/concept-map-image/ ---> link for the concept map png image
    url(r'^(?P<journal_id>\d+)/concept-map-image/$', views.journalConceptMapImage, name='journalConceptMapImage'),

    # /journal/example/concept-map/ ---> displays the example concept map input and output
    url(r'^example/concept-map/$', views.journalExampleConceptMapPage, name='journalExampleConceptMapPage'),
)

# (?P<username>\w+)     ---> w+ indicates a string
# (?P<journal_id>\d+)   ---> d+ indicates a number

sdii/registration/urls.py
# ------------------------------------||------------------------------------- #
#                            registration/urls.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 September 09
# ------------------------------------||------------------------------------- #

from django.conf.urls import patterns, url
from registration import views

urlpatterns = patterns('',
    # /registration/                
    url(r'^$', views.registrationPage, name='registrationPage'),                       
                       
    # /registration/submit                  
    url(r'^submit/$', views.registrationSubmit, name='registrationSubmit'),

    # /registration/activation/resend
    url(r'^activation/resend/$', views.activationResendPage, name='activationResendPage'),

    # /registration/activation/resend
    url(r'^activation/resend/submit/$', views.activationResendSubmit, name='activationResendSubmit'),

    # registration/activation/                  
    url(r'^activation/(?P<code>\w+)$', views.activationPage, name='activationPage'),

    # registration/username/recover
    url(r'^username/recover/$', views.forgotUsernamePage, name='forgotUsernamePage'),

    # registration/username/recover/submit
    url(r'^username/recover/submit/$', views.forgotUsernameSubmit, name='forgotUsernameSubmit'),
)

sdii/sdii/urls.py
# ------------------------------------||------------------------------------- #
#                                 sdii/urls.py
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 August 03
#
# Description:
#   The master url file that routes page requests to the specified locations
# ------------------------------------||--------------------------------------#

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sdii.views.home', name='home'),
    # url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^$', 'home.views.homePage', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^journal/', include('journal.urls', namespace='journal')),
    url(r'^registration/', include('registration.urls', namespace='registration')),

    # DO NOT CHANGE THE FOLLOWING - these are for the operation of the built in authentication for Django
    # Taken from C:\Anaconda\Lib\site-packages\django\contrib\auth\urls.py
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),  
)

sdii/templates/base.html
<!------------------------------------||------------------------------------- #
#                           templates\base.html
#
# Authors: 
#   Benjamin T. Davis
#   NSF Graduate Research Fellow
#   Structural Dynamics and Intelligent Infrastructure Research Group (SDII)
#   University of South Carolina
#   http://sdii.ce.sc.edu/
#
# Date Created: 2014 September 06
#
# Description:
#   The master template for the site layout. All apps build on this.
# ------------------------------------||-------------------------------------->

{% load i18n %}         <!--loads Django translation tags-->
{% load staticfiles %}  <!--loads Django static files-->

<!DOCTYPE html>
<html>

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />    

<div id="wrap">  
    <div id="banner">
        <h1 style="text-align:center">Structural Dynamics and Intelligent Infrastructure</h1>
        <hr />
    </div>
    <div id="userbar">
        <div style="text-align:right">
            {% if user.is_authenticated %}
                {% trans "Welcome," %} {{ user.first_name }} {{ user.last_name }}
                {% if user.is_staff %}
                    (<a href="{% url 'logout' %}">{% trans "Log out" %}</a> | <a href="{% url 'password_change' %}">{% trans "Change password" %}</a> | <a href="{% url 'admin:index' %}" target="_blank">{% trans "Site Admin" %}</a>)
                {% else %}
                    (<a href="{% url 'logout' %}">{% trans "Log out" %}</a> | <a href="{% url 'password_change' %}">{% trans "Change password" %}</a>)
                {% endif %}
            {% else %}
                <a href="{% url 'login' %}">{% trans "Log in" %}</a> | <a href="{% url 'registration:registrationPage' %}">{% trans "Register" %}</a>
            {% endif %}
        </div>
    </div> 
    <div id="navbar">
        {% block nav-global %}
            Navigation
            <hr />
            <a href="{% url 'home' %}">{% trans "Home" %}</a><br>
            <a href="{% url 'journal:journalIndexPage' %}">{% trans "Journals" %}</a><br>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}content{% endblock %}
    </div>   
    <div id="footer">
        <hr />
        {% block footer %}<div style="text-align:center;">University of South Carolina - Columbia</div>{% endblock %}
    </div>
</div>
</html>